-- DoutrinaHUD cloud foundation: authentication profiles, workspaces,
-- teams, players and public sports assets with workspace-scoped writes.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspace_members (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('owner', 'editor', 'viewer')),
  created_at timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  name text not null,
  tag text,
  logo_path text,
  country text,
  color text,
  organization text,
  social_links text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  hltv_url text,
  hltv_team_id text,
  hltv_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, workspace_id)
);

create unique index if not exists teams_workspace_hltv_id_unique
  on public.teams (workspace_id, hltv_team_id)
  where hltv_team_id is not null;

create index if not exists teams_workspace_name_idx
  on public.teams (workspace_id, name);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  team_id bigint,
  nickname text not null,
  real_name text,
  steam_id text,
  steam_link text,
  faceit_link text,
  avatar_path text,
  role text,
  country text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  hltv_player_id text,
  hltv_profile_url text,
  avatar_source text,
  hltv_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint players_team_workspace_fk
    foreign key (team_id, workspace_id)
    references public.teams(id, workspace_id)
    on delete set null (team_id)
);

create unique index if not exists players_workspace_hltv_id_unique
  on public.players (workspace_id, hltv_player_id)
  where hltv_player_id is not null;

create index if not exists players_workspace_nickname_idx
  on public.players (workspace_id, nickname);

create index if not exists players_workspace_team_idx
  on public.players (workspace_id, team_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists workspaces_set_updated_at on public.workspaces;
create trigger workspaces_set_updated_at
before update on public.workspaces
for each row execute function public.set_updated_at();

drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at
before update on public.teams
for each row execute function public.set_updated_at();

drop trigger if exists players_set_updated_at on public.players;
create trigger players_set_updated_at
before update on public.players
for each row execute function public.set_updated_at();

create or replace function public.is_workspace_member(target_workspace_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workspace_members
    where workspace_id = target_workspace_id
      and user_id = auth.uid()
  );
$$;

create or replace function public.can_edit_workspace(target_workspace_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workspace_members
    where workspace_id = target_workspace_id
      and user_id = auth.uid()
      and role in ('owner', 'editor')
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_workspace_id uuid := gen_random_uuid();
  requested_name text;
begin
  requested_name := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
    split_part(new.email, '@', 1),
    'Operador'
  );

  insert into public.profiles (id, display_name)
  values (new.id, requested_name);

  insert into public.workspaces (id, owner_id, name)
  values (new_workspace_id, new.id, requested_name || ' - Workspace');

  insert into public.workspace_members (workspace_id, user_id, role)
  values (new_workspace_id, new.id, 'owner');

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.teams enable row level security;
alter table public.players enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select to authenticated
using (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "workspaces_select_member" on public.workspaces;
create policy "workspaces_select_member"
on public.workspaces for select to authenticated
using (public.is_workspace_member(id));

drop policy if exists "workspaces_insert_owner" on public.workspaces;
create policy "workspaces_insert_owner"
on public.workspaces for insert to authenticated
with check (owner_id = auth.uid());

drop policy if exists "workspaces_update_owner" on public.workspaces;
create policy "workspaces_update_owner"
on public.workspaces for update to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

drop policy if exists "workspaces_delete_owner" on public.workspaces;
create policy "workspaces_delete_owner"
on public.workspaces for delete to authenticated
using (owner_id = auth.uid());

drop policy if exists "workspace_members_select_member" on public.workspace_members;
create policy "workspace_members_select_member"
on public.workspace_members for select to authenticated
using (public.is_workspace_member(workspace_id));

drop policy if exists "workspace_members_manage_owner" on public.workspace_members;
create policy "workspace_members_manage_owner"
on public.workspace_members for all to authenticated
using (
  exists (
    select 1 from public.workspaces
    where id = workspace_id and owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.workspaces
    where id = workspace_id and owner_id = auth.uid()
  )
);

drop policy if exists "teams_select_member" on public.teams;
create policy "teams_select_member"
on public.teams for select to authenticated
using (public.is_workspace_member(workspace_id));

drop policy if exists "teams_insert_editor" on public.teams;
create policy "teams_insert_editor"
on public.teams for insert to authenticated
with check (public.can_edit_workspace(workspace_id));

drop policy if exists "teams_update_editor" on public.teams;
create policy "teams_update_editor"
on public.teams for update to authenticated
using (public.can_edit_workspace(workspace_id))
with check (public.can_edit_workspace(workspace_id));

drop policy if exists "teams_delete_editor" on public.teams;
create policy "teams_delete_editor"
on public.teams for delete to authenticated
using (public.can_edit_workspace(workspace_id));

drop policy if exists "players_select_member" on public.players;
create policy "players_select_member"
on public.players for select to authenticated
using (public.is_workspace_member(workspace_id));

drop policy if exists "players_insert_editor" on public.players;
create policy "players_insert_editor"
on public.players for insert to authenticated
with check (public.can_edit_workspace(workspace_id));

drop policy if exists "players_update_editor" on public.players;
create policy "players_update_editor"
on public.players for update to authenticated
using (public.can_edit_workspace(workspace_id))
with check (public.can_edit_workspace(workspace_id));

drop policy if exists "players_delete_editor" on public.players;
create policy "players_delete_editor"
on public.players for delete to authenticated
using (public.can_edit_workspace(workspace_id));

grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.workspaces to authenticated;
grant select, insert, update, delete on public.workspace_members to authenticated;
grant select, insert, update, delete on public.teams to authenticated;
grant select, insert, update, delete on public.players to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'doutrinahud-assets',
  'doutrinahud-assets',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "doutrinahud_assets_public_read" on storage.objects;
create policy "doutrinahud_assets_public_read"
on storage.objects for select to public
using (bucket_id = 'doutrinahud-assets');

drop policy if exists "doutrinahud_assets_member_insert" on storage.objects;
create policy "doutrinahud_assets_member_insert"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'doutrinahud-assets'
  and public.can_edit_workspace(((storage.foldername(name))[1])::uuid)
);

drop policy if exists "doutrinahud_assets_member_update" on storage.objects;
create policy "doutrinahud_assets_member_update"
on storage.objects for update to authenticated
using (
  bucket_id = 'doutrinahud-assets'
  and public.can_edit_workspace(((storage.foldername(name))[1])::uuid)
)
with check (
  bucket_id = 'doutrinahud-assets'
  and public.can_edit_workspace(((storage.foldername(name))[1])::uuid)
);

drop policy if exists "doutrinahud_assets_member_delete" on storage.objects;
create policy "doutrinahud_assets_member_delete"
on storage.objects for delete to authenticated
using (
  bucket_id = 'doutrinahud-assets'
  and public.can_edit_workspace(((storage.foldername(name))[1])::uuid)
);
